---
sidebar: sidebar 
permalink: reference-soar.html 
keywords: ransomware protection, soar, security orchestration, microsoft sentinel, splunk, automation, threat response, playbook 
summary: Intégrez et utilisez les playbooks SOAR pour automatiser les tâches de réponse aux menaces NetApp Ransomware Resilience. 
---
= Intégrer un playbook SOAR pour NetApp Ransomware Resilience
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ransomware Resilience propose des playbooks d'orchestration, d'automatisation et de réponse en matière de sécurité (SOAR) qui vous permettent d'automatiser des tâches telles que la réponse aux menaces.

Les playbooks Ransomware Resilience offrent les fonctionnalités suivantes :

* Créer un instantané d'un volume
* Enrichir une adresse IP avec des renseignements sur les menaces
* Enrichir les informations de stockage pour un agent et un système donnés
* Mettre un volume hors ligne pour la réponse aux incidents
* Tester la connectivité
* Vérifiez le statut d'un travail d'enrichissement




== Playbooks

Ransomware Resilience propose des guides pratiques pour Microsoft Sentinel et Splunk. Consultez les pages GitHub correspondantes pour les détails de configuration.

* link:https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/NetApp%20Ransomware%20Resilience/Playbooks["Microsoft Sentinel"^]
* link:https://github.com/splunk-soar-connectors/netappransomwareresilience["Splunk"^]



NOTE: Pour Splunk Cloud, vous devez utiliser la version 7.0, 7.1, 7.2, 8.0 ou 8.4 de la plateforme. Pour plus d'informations, consultez link:https://splunkbase.splunk.com/app/8483["Splunkbase"^].



== Plus d'informations

* link:task-siem.html["Connectez NetApp Ransomware Resilience à un SIEM pour l'analyse et la détection des menaces"]

