---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit. 
---
= Limitations connues dans NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.



[[readiness-drill-reset-option-issue]]
== Problème d'option de réinitialisation de l'exercice de préparation

Si vous sélectionnez un volume ONTAP 9.11.1 pour l’exercice de préparation aux attaques de ransomware, Ransomware Resilience envoie une alerte.  Si vous récupérez les données à l'aide de l'option « cloner sur volume » et réinitialisez la perceuse, l'opération de réinitialisation échoue.



[[amazon-fsx-for-netapp-ontap-limitations]]
== Limitations Amazon FSx for NetApp ONTAP

Les limitations suivantes s'appliquent à Amazon FSx pour ONTAP :

* Les stratégies de sauvegarde ne sont pas prises en charge pour Amazon FSx for ONTAP. Dans cet environnement, vous devez effectuer les opérations de sauvegarde à l'aide des sauvegardes Amazon FSx. Vous pouvez restaurer ces charges de travail à l'aide de Ransomware Resilience.
* Les opérations de restauration sont effectuées uniquement à partir de snapshots.




[[azure-netapp-files-limitations]]
== Limitations d'Azure NetApp Files

Les limitations suivantes s'appliquent à Azure NetApp Files :

* Les stratégies de protection contre les ransomwares avec des politiques de sauvegarde ne sont pas prises en charge pour Azure NetApp Files. Vous pouvez utiliser la sauvegarde Azure NetApp Files à la place.
* Les stratégies de protection contre les ransomwares avec réplication ne sont pas prises en charge pour Azure NetApp Files.
* Azure NetApp Files ne prend pas en charge FPolicy ni la détection du comportement des utilisateurs. Azure NetApp Files ne prend pas non plus en charge l'analyse forensique de l'entropie.
* Lors du choix d'une stratégie de protection, assurez-vous que sa fréquence de création d'instantanés est compatible avec Azure NetApp Files. La fréquence de création d'instantanés la plus fréquente disponible dans Azure NetApp Files est horaire.
* Il est recommandé de ne pas utiliser link:reference-soar.html["Playbooks SOAR"] avec Azure NetApp Files, car les API Azure NetApp Files bloquent les actions automatisées.
* Certaines données d'événements ne sont pas incluses dans link:task-siem.html["Rapports SIEM"] pour les configurations Azure NetApp Files.




[[google-cloud-netapp-volumes-limitations]]
== Limitations de Google Cloud NetApp Volumes

Les limitations suivantes s'appliquent à Google Cloud NetApp Volumes :

* Actuellement, vous ne pouvez appliquer que des stratégies de protection basées sur le chiffrement et FPolicy aux charges de travail Google Cloud NetApp Volumes. Vous ne pouvez pas appliquer de stratégies de protection basées sur le comportement des utilisateurs.
* Les stratégies de protection avec réplication ne sont actuellement pas prises en charge pour Google Cloud NetApp Volumes.




[[san-storage-limitations]]
== Limitations du stockage SAN

Les limitations suivantes s'appliquent aux charges de travail SAN (stockage bloc) :

* Lorsque Ransomware Resilience génère des avertissements pour les charges de travail SAN, ces avertissements sont basés uniquement sur une entropie élevée.
* Les charges de travail SAN ne peuvent être restaurées qu'à l'aide d'une link:task-custom-restore.html["restauration personnalisée"]. La restauration propre n'est actuellement pas disponible pour les charges de travail SAN.




[[multi-admin-verification]]
== Vérification multi-administrateurs

La vérification multi-administrateur n'est pas prise en charge dans Ransomware Resilience ni dans la NetApp Console. Si vous avez configuré link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/["Vérification multi-administrateurs dans ONTAP"^], vous ne pourrez pas activer la protection, effectuer un exercice de préparation ni effectuer d'opérations de restauration. Vous devez désactiver la vérification multi-administrateur avant de tenter l'une de ces opérations.
