---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit. 
---
= Limitations connues dans NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.



== Problème d'option de réinitialisation de l'exercice de préparation

Si vous sélectionnez un volume ONTAP 9.11.1 pour l’exercice de préparation aux attaques de ransomware, Ransomware Resilience envoie une alerte.  Si vous récupérez les données à l'aide de l'option « cloner sur volume » et réinitialisez la perceuse, l'opération de réinitialisation échoue.



== Limitations Amazon FSx for NetApp ONTAP

Les limitations suivantes s'appliquent à Amazon FSx pour ONTAP :

* Les stratégies de sauvegarde ne sont pas prises en charge pour Amazon FSx for ONTAP. Dans cet environnement, vous devez effectuer les opérations de sauvegarde à l'aide d'Amazon FSx for ONTAP. Vous pouvez restaurer ces charges de travail grâce à Ransomware Resilience.
* Les opérations de restauration sont effectuées uniquement à partir de snapshots.




== Limitations d'Azure NetApp Files

Les limitations suivantes s'appliquent à Azure NetApp Files :

* Les stratégies de protection contre les ransomwares avec des politiques de sauvegarde ne sont pas prises en charge pour Azure NetApp Files. Vous pouvez utiliser la sauvegarde Azure NetApp Files à la place.
* Les stratégies de protection contre les ransomwares avec réplication ne sont pas prises en charge pour Azure NetApp Files.
* Azure NetApp Files ne prend pas en charge FPolicy ni la détection du comportement des utilisateurs. Azure NetApp Files ne prend pas non plus en charge l'analyse forensique de l'entropie.
* Lors du choix d'une stratégie de protection, assurez-vous que sa fréquence de création d'instantanés est compatible avec Azure NetApp Files. La fréquence de création d'instantanés la plus fréquente disponible dans Azure NetApp Files est horaire.
* Il est recommandé de ne pas utiliser link:reference-soar.html["Playbooks SOAR"] avec Azure NetApp Files, car les API Azure NetApp Files bloquent les actions automatisées.
* Certaines données d'événements ne sont pas incluses dans link:task-siem.html["Rapports SIEM"] pour les configurations Azure NetApp Files.




== Limitations de Google Cloud NetApp Volumes

Les limitations suivantes s'appliquent à Google Cloud NetApp Volumes :

* Les charges de travail SAN provenant de Google Cloud NetApp Volumes ne sont actuellement pas prises en charge par Ransomware Resilience.
* Actuellement, vous ne pouvez appliquer que des stratégies de protection basées sur le chiffrement et FPolicy aux charges de travail Google Cloud NetApp Volumes. Vous ne pouvez pas appliquer de stratégies de protection basées sur le comportement des utilisateurs.
* Les stratégies de protection avec réplication ne sont actuellement pas prises en charge pour Google Cloud NetApp Volumes

