---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Pour utiliser Ransomware Resilience, effectuez quelques étapes pour le configurer. 
---
= Configurer la NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configurez la solution NetApp Ransomware Resilience en préparant une destination de sauvegarde, en examinant les prérequis et en configurant la NetApp Console et l’agent Console.



[[prepare-the-backup-destination]]
== Préparer la destination de sauvegarde

Préparez l’une des destinations de sauvegarde suivantes :

* NetApp StorageGRID
* Amazon Web Services
* Plateforme Google Cloud
* Microsoft Azure


Après avoir configuré les options dans la destination de sauvegarde elle-même, vous la configurerez ensuite comme destination de sauvegarde dans NetApp Ransomware Resilience. Pour plus de détails sur la façon de configurer la destination de sauvegarde dans NetApp Ransomware Resilience, reportez-vous à link:task-backup-destination.html["Configurer les destinations de sauvegarde"].



[[prepare-storagegrid-to-become-a-backup-destination]]
=== Préparez StorageGRID pour devenir une destination de sauvegarde

Si vous souhaitez utiliser StorageGRID comme destination de sauvegarde, reportez-vous à https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentation de StorageGRID"^] pour plus de détails sur StorageGRID.



[[prepare-aws-to-become-a-backup-destination]]
=== Préparez AWS à devenir une destination de sauvegarde

* Configurez un compte dans AWS.
* Configure https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Autorisations AWS"^] dans AWS.


Pour plus de détails sur la gestion de votre stockage AWS dans la console, reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Gérez vos buckets Amazon S3"^] .



[[prepare-azure-to-become-a-backup-destination]]
=== Préparez Azure à devenir une destination de sauvegarde

* Configurez un compte dans Azure.
* Configure https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Autorisations Azure"^] dans Azure.


Pour plus de détails sur la gestion de votre stockage Azure dans la console, reportez-vous à https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Gérez vos comptes de stockage Azure"^] .



[[set-up-the-netapp-console]]
== Configurer la NetApp Console

L'étape suivante consiste à configurer la NetApp Console et la résilience aux ransomwares.

Revoir https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Configuration requise pour la console en mode standard"^] .



[[create-a-console-agent]]
=== Créer un agent de console

Contactez votre représentant commercial NetApp pour essayer ou utiliser ce service. L’agent Console inclut alors les fonctionnalités nécessaires à la résilience face aux ransomwares.

Pour créer un agent Console pour Ransomware Resilience, contactez l'administrateur de votre organisation Console qui dispose de l'autorisation de créer des agents Console et consultez  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["comment créer un agent de console"^].


NOTE: Si vous disposez de plusieurs agents Console, Ransomware Resilience analyse les données de tous les agents Console, pas seulement de celui actuellement affiché dans la Console. Le service analyse les données de tous les projets et agents Console associés à l'organisation.
