---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Trouvez une réponse à une question fréquemment posée sur la NetApp Ransomware Resilience. 
---
= FAQ sur la résilience face aux ransomwares NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous recherchez simplement une réponse rapide à une question sur NetApp Ransomware Resilience.



== Déploiement

.Avez-vous besoin d'une licence pour utiliser Ransomware Resilience ?
Vous pouvez utiliser les types de licences suivants :

* Inscrivez-vous pour un essai gratuit de 30 jours.
* Achetez un abonnement à la carte (PAYGO) à NetApp Intelligent Services et Ransomware Resilience avec Amazon Web Services (AWS) Marketplace, Google Cloud Marketplace et Microsoft Azure Marketplace.
* Apportez votre propre licence (BYOL), qui est un fichier de licence NetApp (NLF) que vous obtenez auprès de votre représentant commercial NetApp . Vous pouvez utiliser le numéro de série de la licence pour activer le BYOL dans la section Licenses and subscriptions de la console.


.Comment activer la résilience aux ransomwares ?
Vous pouvez accéder à Ransomware Resilience depuis la NetApp Console. Assurez-vous d'avoir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["rôles d'accès"] et link:rp-start-prerequisites.html["prérequis"]. Si vous avez correctement configuré un agent de console, vous pouvez alors : link:rp-start-discover.html["découvrir les charges de travail"].

Pour plus d'informations, voirlink:rp-start-login.html["Accéder à la résilience des ransomwares"] etlink:rp-start-quick-start.html["Guide de démarrage rapide de Ransomware Resilience"] .

.La solution Ransomware Resilience est-elle disponible en modes standard, restreint et privé ?
Ransomware Resilience n'est actuellement disponible qu'en mode standard.

Pour une explication sur ces modes dans tous les services de données NetApp , reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"^] .

.Comment fonctionne la facturation de Ransomware Resilience ?
Vous pouvez essayer Ransomware Resilience avec un essai gratuit de 30 jours. NetApp ne vous facture pas l'utilisation de la version d'essai de Ransomware Resilience.

Si vous disposez à la fois de Backup and Recovery et de Ransomware Resilience, toutes les données communes protégées par les deux produits sont facturées uniquement par Ransomware Resilience.

Lorsqu'une charge de travail est classée comme protégée, elle est déduite de la capacité achetée ou de l'abonnement PAYGO. Ransomware Resilience classe une charge de travail comme protégée lorsqu'une stratégie de détection est activée avec au moins une règle de sauvegarde ou d'instantané. Les charges de travail détectées avec une stratégie de détection mais  aucune règle de sauvegarde ou d'instantané sont classées comme à risque. Les charges de travail à risque ne sont pas déduites de la capacité achetée.

Les charges de travail protégées sont déduites de la capacité achetée ou de l’abonnement après la période d’essai gratuite. Ransomware Resilience est facturé au Go pour les données associées aux charges de travail protégées (telles que rapportées par ONTAP) avant application des gains d’efficacité.

Pour le dimensionnement, les coûts de licence sont basés sur la capacité logique du système de fichier actif (l’espace consommé par les snapshots n’est donc pas inclus).



== Accéder

.Quelle est l'URL de résilience face aux ransomwares ?
Dans un navigateur, saisissez https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] pour accéder à la console.

.Comment les autorisations d'accès sont-elles gérées ?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la console pour tous les services"^]. Ransomware Resilience possède également link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["rôles d'accès dédiés"^].

.Quelle est la meilleure résolution d'écran ?
La résolution d'appareil recommandée pour Ransomware Resilience est de 1920 x 1080 ou supérieure.

.Quel navigateur dois-je utiliser ?
Vous pouvez accéder à la NetApp Console avec n'importe quel navigateur Web moderne.



== Interopérabilité

.La résilience face aux ransomwares est-elle consciente des paramètres de protection dans ONTAP?
Oui, Ransomware Resilience découvre les planifications de snapshots définies dans ONTAP.

.Comment la résilience face aux ransomwares interagit-elle avec NetApp Backup and Recovery ?
Ransomware Resilience fonctionne avec Backup and Recovery pour découvrir et définir des stratégies d'instantané et de sauvegarde pour les charges de travail de partage de fichiers. Ransomware Resilience fonctionne également avec Backup and Recovery pour effectuer une restauration cohérente des fichiers et des charges de travail.

Pour la gestion des licences et la facturation, Ransomware Resilience peut s'intégrer à Backup and Recovery même si vous ne disposez pas d'une licence distincte pour Backup and Recovery. Si vous disposez à la fois de Backup and Recovery et de Ransomware Resilience, toutes les données communes protégées par les deux produits sont facturées uniquement par Ransomware Resilience.



== Charges de travail

.Qu’est-ce qu’une charge de travail dans le contexte de la résilience aux ransomwares ?
Une charge de travail est une machine virtuelle ou un partage de fichiers.

.Comment Ransomware Resilience priorise-t-il les données de charge de travail ?
La priorité de la charge de travail (critique, standard, importante) est déterminée par les fréquences de snapshots déjà appliquées à chaque volume associé à la charge de travail et aux sauvegardes planifiées.

link:rp-use-protect.html["En savoir plus sur la priorité ou l'importance de la charge de travail"] .

.Quelles charges de travail la résilience face aux ransomwares prend-elle en charge ?
Ransomware Resilience peut identifier les charges de travail suivantes : Oracle, partages de fichiers, stockage par blocs, machines virtuelles et banques de données de machines virtuelles.

.Comment associer des données à une charge de travail ?
Ransomware Resilience détecte les volumes et les extensions de fichiers et les associe à la charge de travail appropriée.

.Qu'est-ce qu'une charge de travail protégée ?
Dans Ransomware Resilience, une charge de travail affiche l'état *protégé* lorsqu'une stratégie de _détection_ principale est activée, ce qui signifie link:concept-ransomware-resilience.html["Protection autonome contre les ransomwares (ARP)"] est activé sur tous les volumes liés à la charge de travail.

.Qu’est-ce qu’une charge de travail « à risque » ?
Si une charge de travail ne dispose pas d'une stratégie de détection principale activée, elle est considérée comme « à risque », même si une stratégie de sauvegarde et de capture instantanée est activée. Pour vous protéger contre les ransomwares, vous devez activer un link:rp-use-protect.html#add-a-ransomware-protection-strategy["politique de détection"].

.J'ai ajouté un nouveau volume, mais il n'est pas encore apparu. Que dois-je faire?
Si vous avez ajouté un nouveau volume à votre environnement, relancez la découverte de la charge de travail. Une fois le volume découvert, link:rp-use-protect.html#add-a-ransomware-protection-strategy["appliquer des politiques de protection pour protéger le nouveau volume"].



== Politiques de protection

.Les politiques de résilience aux ransomwares peuvent-elles coexister avec d'autres types de politiques de charge de travail ?
À l’heure actuelle, la sauvegarde et la récupération (Cloud Backup) prennent en charge une politique de sauvegarde par volume. Si vous configurez la protection de sauvegarde avec Backup and Recovery, celle-ci partage les mêmes politiques de sauvegarde avec Ransomware Resilience.

Les copies instantanées ne sont pas limitées et peuvent être ajoutées séparément de chaque service.

.Quelles sont les politiques requises dans une stratégie de protection contre les ransomwares ?
UN link:rp-use-protect.html#add-a-ransomware-protection-strategy["stratégie de protection contre les ransomwares"] nécessite :

* une politique de détection des ransomwares, et
* une politique d'instantané


Une politique de sauvegarde n’est pas requise dans la stratégie de résilience aux ransomwares.

.La résilience face aux ransomwares est-elle consciente des paramètres de protection dans ONTAP?
Oui, Ransomware Resilience détecte les planifications de snapshots définies dans ONTAP. Il détecte également si ARP et FPolicy sont activés sur tous les volumes d'une charge de travail détectée. Les informations affichées dans le tableau de bord Ransomware Resilience proviennent d'autres NetApp solutions et produits.

.La fonction Ransomware Resilience prend-elle en compte les politiques déjà définies dans NetApp Backup and Recovery ?
Oui, si vous avez des charges de travail gérées dans Backup and Recovery, les politiques gérées par ces produits sont intégrées à Ransomware Resilience.

.Est-il possible de modifier les politiques reportées depuis NetApp Backup and Recovery ?
Non, vous ne pouvez pas modifier les politiques gérées par Backup and Recovery depuis Ransomware Resilience. Vous gérez toute modification de ces politiques dans Backup and Recovery.

.Si des politiques existent depuis ONTAP (telles que ARP, FPolicy et les instantanés), sont-elles modifiées dans Ransomware Resilience ?
Non. Ransomware Resilience ne modifie aucune politique de détection existante (paramètres ARP, FPolicy) d' ONTAP.

.Que se passe-t-il si vous ajoutez de nouvelles politiques dans Backup and Recovery après avoir souscrit à Ransomware Resilience ?
Ransomware Resilience reconnaît les nouvelles politiques créées et les modifications de politiques dans Backup and Recovery.

.Est-il possible de modifier les politiques depuis ONTAP?
Oui, vous pouvez modifier les politiques d’ ONTAP dans Ransomware Resilience.  Vous pouvez également créer de nouvelles politiques dans Ransomware Resilience et les appliquer aux charges de travail.  Cette action remplace les politiques ONTAP existantes par les politiques créées dans Ransomware Resilience.

.Est-il possible de désactiver les politiques dans ONTAP?
Vous pouvez désactiver ARP dans les politiques de détection à l'aide de l'interface utilisateur, des API ou de l'interface de ligne de commande du gestionnaire système dans ONTAP.

Vous pouvez désactiver FPolicy et les stratégies de sauvegarde en appliquant une stratégie différente qui ne les inclut pas.
