---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: Commencez à utiliser NetApp Ransomware Resilience en vérifiant la prise en charge de votre environnement, de votre accès réseau, de votre connexion et de votre navigateur Web. 
---
= Conditions préalables à la NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Commencez par vérifier la préparation de votre environnement opérationnel, de votre accès réseau et de votre navigateur Web afin d'évaluer la NetApp Ransomware Resilience .

Pour utiliser Ransomware Resilience, assurez-vous de remplir les conditions préalables.



== Systèmes pris en charge

Assurez-vous d'utiliser un système pris en charge :

|===
| Environnement | Protocole | Versions prises en charge 


| Amazon FSx for NetApp ONTAP* | NFS, CIFS et SAN | S/O 


.2+| Cloud Volumes ONTAP pour AWS | CIFS et NFS | 9.11.1 et versions ultérieures 


| SAN (FC, iSCSI et NVMe) | 9.17.1 et versions ultérieures 


.2+| Cloud Volumes ONTAP pour Google Cloud Platform | CIFS et NFS | 9.11.1 et versions ultérieures 


| SAN (FC, iSCSI et NVMe) | 9.17.1 et versions ultérieures 


.2+| Cloud Volumes ONTAP pour Microsoft Azure | CIFS et NFS | 9.12.1 et versions ultérieures 


| SAN (FC, iSCSI et NVMe) | 9.17.1 et versions ultérieures 


.2+| ONTAP (sur site) | CIFS et NFS | 9.11.1 et versions ultérieures 


| SAN (FC, iSCSI et NVMe) | 9.17.1 et versions ultérieures 
|===
Amazon FSx for NetApp ONTAP utilise la protection autonome contre les ransomwares (ARP) et non ARP/AI.  Pour plus d'informations sur la différence, voirlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/IA"^] .



== Configuration requise NetApp Console

La configuration de votre NetApp Console requiert :

* Un compte utilisateur de la NetApp Console avec des privilèges d’administrateur d’organisation pour la découverte des ressources.
* Une organisation et un système de console avec au moins un agent de console actif connecté à unlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["système pris en charge"] .
+
** Si vos clusters ONTAP locaux ou Cloud Volumes ONTAP dans AWS ou dans le cloud Azure ne sont pas configurés dans la console, consultezlink:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Apprenez à configurer un agent de console"^] etlink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["exigences standard de la console"^] .
+

NOTE: Si vous disposez de plusieurs agents de console dans une seule organisation de console, Ransomware Resilience analysera les ressources ONTAP sur tous les agents de console au-delà de celui actuellement sélectionné dans l'interface utilisateur de la console.



* L'agent de la console doit avoir le `cloudmanager-ransomware-protection` conteneur dans un état actif.
* Au moins un système de console avec un cluster ONTAP sur site NetApp ou Cloud Volumes ONTAP dans AWS ou Azure.  Ransomware Resilience prend en charge les protocoles NAS (NFS et SMB) et SAN (iSCSI, FC et NVMe).
+
** La résilience aux ransomwares est prise en charge avec les clusters ONTAP ou Cloud Volumes ONTAP avec la version ONTAP 9.11.1 ou supérieure.
+

NOTE: Pour utiliser Ransomware Resilience sur les charges de travail SAN, vous devez exécuter ONTAP 9.17.1 ou une version ultérieure.







== Exigences ONTAP

* Vous devez utiliser ONTAP 9.11.1 ou une version ultérieure avec une licence ONTAP One activée sur l'instance ONTAP locale.  Pour plus d'informations sur la prise en charge ONTAP , consultezlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Présentation de la protection autonome contre les ransomwares"^] .
* Pour appliquer des configurations de protection (telles que l'activation de la protection autonome contre les ransomwares), Ransomware Resilience a besoin de droits d'administrateur sur le cluster ONTAP . Le cluster ONTAP aurait dû être intégré à l’aide des informations d’identification de l’utilisateur administrateur du cluster ONTAP uniquement.



NOTE: Si vous avez connecté un cluster ONTAP à la console avec des informations d'identification non administrateur, [vous devez mettre à jour les informations d'identification dans le cluster ONTAP ](#update-non-admin-user-permissions-in-an-ontap-system).



== Sauvegardes de données

* Un compte dans NetApp StorageGRID, AWS S3, Azure Blob ou Google Cloud Platform pour les cibles de sauvegarde avec les autorisations d'accès appropriées configurées.
+
Se référer à la https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Liste des autorisations AWS, Azure ou S3"^] pour plus de détails.

* NetApp Backup and Recovery n’a pas besoin d’être activé sur le système.
+
Ransomware Resilience permet de configurer une destination de sauvegarde via l'option Paramètres. Voir link:rp-use-settings.html["Configurer les paramètres"] .





== Comportement suspect de l'utilisateur

Pour que Ransomware Resilience fournisse des alertes sur les comportements suspects des utilisateurs, vous devez configurer un agent d’activité utilisateur. Pour plus d'informations, voir link:suspicious-user-activity.html["Configurer la détection des activités suspectes des utilisateurs dans NetApp Ransomware Resilience"].



== Mettre à jour les autorisations des utilisateurs non administrateurs dans un système ONTAP

Si vous devez mettre à jour les autorisations des utilisateurs non administrateurs pour un système particulier, procédez comme suit.

. Connectez-vous à la console et recherchez le système dont les autorisations utilisateur ONTAP doivent être mises à jour.
. Sélectionnez le système pour voir les détails.
. Sélectionnez *Afficher les informations supplémentaires* pour afficher le nom d'utilisateur.
. Connectez-vous à l'interface de ligne de commande du cluster ONTAP en tant qu'utilisateur administrateur.
. Afficher les rôles existants pour cet utilisateur. Entrer:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Modifier le rôle de l'utilisateur. Entrer:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Retournez à la NetApp Console pour utiliser la résilience face aux ransomwares.

