---
sidebar: sidebar 
permalink: rp-use-overview.html 
keywords: ransomware protection, ransomware protection, detect ransomware attacks, recover from ransomware attack 
summary: Grâce à NetApp Ransomware Resilience, vous pouvez afficher l’état de la charge de travail et protéger les charges de travail. 
---
= Utiliser la NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Avec NetApp Ransomware Resilience, vous pouvez afficher l'état de la charge de travail et protéger les charges de travail.

* link:rp-start-discover.html["Découvrez les charges de travail dans Ransomware Resilience"] .
* link:rp-use-dashboard.html["Afficher la protection et l'état de la charge de travail à partir du tableau de bord"] .
+
** Examinez et appliquez les recommandations de protection contre les ransomwares.


* link:rp-use-protect.html["Protéger les charges de travail"]:
+
** Attribuez une stratégie de protection contre les ransomwares aux charges de travail.
** Augmentez la protection des applications pour prévenir de futures attaques de ransomware.
** Créer, modifier ou supprimer une stratégie de protection.


* link:rp-use-alert.html["Répondre à la détection d'attaques potentielles de ransomware"] .
* link:rp-use-recover.html["Se remettre d'une attaque"](après que les incidents soient neutralisés).
* link:rp-use-settings.html["Configurer les paramètres de protection"] .

