---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, block user, stop alerts, exclude users, alert management 
summary: 'Après avoir créé le connecteur d"annuaire utilisateur dans NetApp Ransomware Resilience, vous pouvez bloquer et débloquer des utilisateurs et exclure des utilisateurs des alertes. Vous pouvez également exclure des chemins de fichiers de la génération d"alertes.' 
---
= Gérez les alertes et les utilisateurs bloqués dans NetApp Ransomware Resilience
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Après avoir configuré la détection d'activité des utilisateurs dans NetApp Ransomware Resilience, vous pouvez gérer les utilisateurs bloqués et personnaliser les alertes. Vous pouvez exclure des utilisateurs ou des chemins de fichiers spécifiques des alertes, et vous pouvez bloquer des utilisateurs en réponse à des événements liés à des ransomwares afin de prévenir toute activité malveillante.

Vous devez avoir link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["configuré un agent d'activité utilisateur, activé une stratégie avec détection d'activité utilisateur et créé un connecteur d'annuaire utilisateur"] pour bloquer les utilisateurs.


TIP: Vous pouvez link:task-automate-user-activity.html["automatiser les réponses"] aux événements de détection d'activité utilisateur.



[[manage-blocked-users]]
== Gérer les utilisateurs bloqués

Vous pouvez bloquer les utilisateurs lorsque vous pensez qu'ils sont responsables d'activités malveillantes.

.Bloquer les utilisateurs
. Dans Ransomware Resilience, sélectionnez **Paramètres**.
. Dans le tableau de bord Paramètres, repérez la vignette de surveillance de l'activité de l'utilisateur, puis sélectionnez **Gérer**.
. Sélectionnez l’onglet **Utilisateurs**.
. Sélectionnez **Bloquer les utilisateurs**.
. Choisissez la durée du blocage. Vous pouvez bloquer les utilisateurs définitivement ou définir un blocage d'une durée comprise entre 1 et 24 heures.
. Cochez la case en regard des noms des utilisateurs que vous souhaitez bloquer.
. Sélectionnez **Block**.


.Modifier la liste des utilisateurs bloqués
. Dans Ransomware Resilience, sélectionnez **Paramètres**.
. Dans le tableau de bord Paramètres, repérez la vignette de surveillance de l'activité de l'utilisateur, puis sélectionnez **Gérer**.
. Sélectionnez l’onglet **Utilisateurs**.
. Sélectionnez **Modifier le blocage des utilisateurs**.
. Choisissez le type de blocage d'utilisateurs que vous souhaitez modifier. Pour modifier la durée du blocage, sélectionnez **Période de blocage pour les utilisateurs bloqués** puis modifiez la **Période**. Pour retirer des utilisateurs de la liste des utilisateurs bloqués, sélectionnez **Débloquer les utilisateurs**.
. Cochez la case en regard du nom de l'utilisateur bloqué dont vous souhaitez modifier le statut.
. Sélectionnez **Enregistrer**.




[[exclude-users-from-alerts]]
== Exclure les utilisateurs des alertes

S'il existe certains utilisateurs de confiance dont le comportement pourrait déclencher des alertes de comportement utilisateur, vous pouvez les exclure des alertes.

.Exclure les utilisateurs des alertes
. Dans Ransomware Resilience, sélectionnez **Paramètres**.
. Dans le tableau de bord Paramètres, repérez la vignette de surveillance de l'activité de l'utilisateur, puis sélectionnez **Gérer**.
. Sélectionnez l'onglet **Exclu de la surveillance**.
. Pour consulter les utilisateurs individuellement dans l'interface utilisateur, choisissez **Select manually**. Pour importer une liste d'utilisateurs exclus, sélectionnez **Upload**.
+
.. Si vous avez sélectionné **Select manually**, cochez la case en regard des noms des utilisateurs spécifiques que vous souhaitez exclure.
.. Si vous sélectionnez **Upload**, téléchargez le fichier CSV ou JSON contenant la liste de tous les utilisateurs. Sélectionnez **Download** pour accéder à la liste.
+
Sur votre ordinateur local, examinez le fichier. Supprimez les noms de tous les utilisateurs pour lesquels vous souhaitez maintenir la détection. Lorsque la liste ne contient plus que les noms des utilisateurs que vous souhaitez exclure de la détection, enregistrez-la.

+
Dans NetApp Ransomware Resilience, sélectionnez **Téléverser**. Localisez et téléversez le fichier.



. Sélectionnez **Ajouter** pour terminer l’ajout des utilisateurs à la liste d’exclusion.
. Dans l'onglet **Exclu de la surveillance**, les noms des utilisateurs retirés des alertes de détection du comportement des utilisateurs s'affichent désormais dans le tableau de bord.



TIP: Vous pouvez également exclure un utilisateur directement d'une alerte. Pour plus d'informations, consultez link:rp-use-alert.html["Répondre aux alertes de ransomware"].

.Supprimer les utilisateurs de la liste des utilisateurs exclus
. Dans le tableau de bord Paramètres, repérez la carte User activity puis sélectionnez **Manage**.
. Sélectionnez l'onglet **Exclu de la surveillance**.
. Sélectionnez **Ajouter**.
. Pour exclure des utilisateurs individuels de l'interface utilisateur, choisissez **Select manually**.
. Repérez le nom de l'utilisateur que vous souhaitez supprimer de la liste des utilisateurs exclus. Sélectionnez le menu d'actions (`...` sur la ligne contenant le nom de l'utilisateur, puis **Supprimer**.
. Dans la boîte de dialogue, sélectionnez **Remove** pour confirmer que vous souhaitez supprimer les utilisateurs sélectionnés.




[[exclude-file-paths-from-monitoring]]
== Exclure les chemins d'accès aux fichiers de la surveillance

Chaque chemin d'accès doit commencer par le nom d'un volume. Il peut inclure jusqu'à trois sous-répertoires pour ce volume, par exemple "volume/répertoire/sous-répertoire/sous-répertoire2". Vous pouvez exclure des chemins d'accès en les saisissant manuellement ou en important un fichier CSV qui les répertorie.

.Étapes
. Dans Ransomware Resilience, sélectionnez **Paramètres**.
. Dans la vignette de surveillance de l'activité de l'utilisateur, sélectionnez **Gérer**.
. Sélectionnez l’onglet *Exclu de la surveillance*.
. Sélectionnez **Ajouter** pour saisir les chemins d'accès aux fichiers à exclure.
. Pour saisir les chemins d'accès aux fichiers dans l'interface utilisateur, sélectionnez le bouton radio *Saisie manuelle*, puis saisissez le chemin d'accès, par exemple "volume/directory/subdirectory/". Pour saisir d'autres chemins d'accès, sélectionnez **Select file path**.
. Pour importer une liste de chemins de fichiers, sélectionnez l’option **Importer**. Sélectionnez le bouton d’importation pour choisir le fichier CSV.
. Sélectionnez **Ajouter**.


.Résultat
Une fois l'opération terminée avec succès, NetApp Ransomware Resilience commence à exclure les fichiers situés dans les chemins sélectionnés de la surveillance des comportements suspects des utilisateurs. Vous pouvez consulter la liste des chemins à tout moment dans le menu Paramètres. Si vous devez réactiver la surveillance de ces chemins de fichiers, vous pouvez les retirer de la liste.



[[next-steps]]
== Prochaines étapes

* link:task-automate-user-activity.html["Automatisez les réponses aux événements de détection d'activité des utilisateurs"]

