= Évaluation des risques de sécurité par Digital Advisor
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Évaluation des risques de sécurité par Digital Advisor

La protection contre les ransomwares BlueXP collecte désormais des informations sur les risques de sécurité élevés et critiques du cluster auprès de NetApp Digital Advisor. En cas de risque détecté, la protection contre les ransomwares BlueXP affiche cette recommandation dans le volet *Actions recommandées* du tableau de bord : « Corrigez une vulnérabilité de sécurité connue sur le cluster <name>. » Depuis la recommandation du tableau de bord, sélectionnez *Examiner et corriger* pour consulter Digital Advisor et l’article Common Vulnerability & Exposure (CVE) associé. S’il existe plusieurs risques de sécurité, consultez les détails dans Digital Advisor.

Se référer à https://docs.netapp.com/us-en/active-iq/index.html["Documentation du Digital Advisor"^] .



[[back-up-to-google-cloud-platform]]
=== Sauvegarde sur Google Cloud Platform

Avec cette version, vous pouvez définir une destination de sauvegarde sur un bucket Google Cloud Platform.  Auparavant, vous pouviez ajouter des destinations de sauvegarde uniquement à NetApp StorageGRID, Amazon Web Services et Microsoft Azure.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["En savoir plus sur la configuration des paramètres de BlueXP ransomware protection"].



[[support-for-google-cloud-platform]]
=== Prise en charge de Google Cloud Platform

Le service prend désormais en charge Cloud Volumes ONTAP pour Google Cloud Platform pour la protection du stockage.  Auparavant, le service prenait uniquement en charge Cloud Volumes ONTAP pour Amazon Web Services et Microsoft Azure ainsi que le NAS sur site.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["En savoir plus sur la BlueXP ransomware protection et les sources de données prises en charge, les destinations de sauvegarde et les environnements de travail"] .



[[role-based-access-control]]
=== Contrôle d'accès basé sur les rôles

Vous pouvez désormais limiter l’accès à des activités spécifiques grâce au contrôle d’accès basé sur les rôles (RBAC).  La BlueXP ransomware protection utilise deux rôles de BlueXP: administrateur de compte BlueXP et administrateur non-compte (spectateur).

Pour plus de détails sur les actions que chaque rôle peut effectuer, voir https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Privilèges de contrôle d'accès basés sur les rôles"] .
