= La BlueXP ransomware protection est désormais NetApp Ransomware Resilience
:allow-uri-read: 




=== La BlueXP ransomware protection est désormais NetApp Ransomware Resilience

Le service de BlueXP ransomware protection a été renommé NetApp Ransomware Resilience.



=== BlueXP est désormais NetApp Console

La console NetApp offre une gestion centralisée des services de stockage et de données dans les environnements sur site et dans le cloud à l'échelle de l'entreprise, offrant des informations en temps réel, des flux de travail plus rapides et une administration simplifiée.

Pour plus de détails sur ce qui a changé, consultez le https://docs.netapp.com/us-en/console-relnotes/index.html["Notes de version de la console NetApp"] .



=== Détection de violation de données

Ransomware Resilience inclut un nouveau mécanisme de détection qui peut être activé en quelques étapes pour détecter les lectures anormales des utilisateurs comme indicateur précoce d'une violation de données.  La résilience des ransomwares collecte et analyse les événements de lecture des utilisateurs en créant une base de référence historique, qui est un profil du comportement normal attendu à partir des données passées.  Lorsque l'activité d'un nouvel utilisateur s'écarte considérablement de cette norme établie (comme une augmentation inattendue des lectures associée à des modèles de lecture suspects), une alerte est générée.  Ransomware Resilience inclut un modèle d'IA pour détecter les modèles de lecture suspects.

Contrairement à la détection de chiffrement par ARP au niveau de la couche de stockage, la détection de l'anomalie de comportement de l'utilisateur est effectuée dans le service SaaS Ransomware Resilience en collectant les événements FPolicy.

Pour plus d'informations, voirlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.htm["Activer la détection des activités suspectes des utilisateurs"] etlink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html#view-anomalous-user-behavior["Afficher le comportement anormal des utilisateurs"] .



==== Détections supplémentaires d'activités suspectes d'utilisateurs

En plus de la détection des violations de données, Ransomware Resilience détecte également les types d'alertes suivants en fonction de l'activité suspecte observée des utilisateurs :

* **Destruction de données - attaque potentielle** - Une alerte avec la gravité d'une attaque potentielle est créée lorsque le nombre de suppressions de fichiers dépasse la norme historique.
* **Comportement suspect de l'utilisateur - attaque potentielle** - Une alerte avec la gravité d'une attaque potentielle est créée lorsque des opérations de lecture, de renommage et de suppression dans une séquence similaire à une attaque de ransomware sont observées
* **Comportement suspect de l'utilisateur - Avertissement** - Une alerte avec la gravité d'un avertissement est créée lorsque le nombre total d'activités de fichiers (lecture, suppression, renommage, etc.) dépasse la norme historique




==== Nouveau rôle d'utilisateur pour la détection des violations de données

Pour gérer les alertes d'activité suspecte des utilisateurs, Ransomware Resilience a introduit deux nouveaux rôles pour fournir un accès granulaire aux données sensibles telles que l'activité des fichiers de l'utilisateur. Pour plus d'informations, consultez la section link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Accès basé sur les rôles NetApp Ransomware Resilience"] .
