= Prise en charge de Google Cloud NetApp Volumes (aperçu)
:allow-uri-read: 




=== Prise en charge de Google Cloud NetApp Volumes (aperçu)

Ransomware Resilience prend désormais en charge les systèmes Google Cloud NetApp Volumes, vous permettant de détecter et de contrer efficacement les menaces de ransomware dans Google Cloud NetApp Volumes. Lorsque vous effectuez une découverte, Ransomware Resilience affiche automatiquement les charges de travail provenant des systèmes Google Cloud NetApp Volumes. Lorsque vous découvrez les systèmes, ils apparaissent dans le tableau de bord de Ransomware Resilience. La prise en charge de Google Cloud NetApp Volumes dans Ransomware Resilience est actuellement en préversion.

Pour plus d'informations, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["En savoir plus sur la résilience aux ransomwares"^]. Pour des informations sur l'étendue de la prise en charge de Google Cloud NetApp Volumes, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Limites de la résilience face aux ransomwares"^].



=== Améliorations de la restauration propre

La restauration complète prend désormais en charge les rapports. Grâce aux rapports, vous pouvez consulter et évaluer les restaurations complètes, en enregistrant ces informations hors ligne au format CSV.

La restauration propre permet désormais d'interrompre l'analyse. Si vous interrompez l'analyse, vous devez recommencer la restauration propre.

Pour en savoir plus sur les rapports, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Télécharger les rapports dans Ransomware Resilience"^]. Pour en savoir plus sur la récupération, consultez link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Récupérez les charges de travail avec une restauration propre"^].
